apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesStrategicMerge:
  - validator-patch.yaml
  - config-patch.yaml

# Local: build image from source
# kind load docker-image pwntensor-validator:local
