apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pwntensor

resources:
  - namespace.yaml
  - configmap.yaml
  - nginx-configmap.yaml
  - validator-deployment.yaml
  - service.yaml
  - miner-deployment.yaml
  - miner-service.yaml
