apiVersion: v1
kind: ConfigMap
metadata:
  name: pwntensor-config
  namespace: pwntensor
data:
  # Staging: hit Bittensor testnet
  NETWORK: "test"
  NETUID: "1"
  LOG_LEVEL: "INFO"
  FRONTEND_PORT: "8080"
